Assignment1/Assignment1/Models/Lesson.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assignment1.Models
{
    public class Lesson
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Student")]
        [ForeignKey("Student")]
        public int StudentId { get; set; }


        [Display(Name = "Instrument")]
        [ForeignKey("Instrument")]
        public int InstrumentId { get; set; }

        [Display(Name = "Tutor")]
        [ForeignKey("Tutor")]
        public int TutorId { get; set; }

        [Display(Name ="Lesson Date")]
        [DataType(DataType.Date)]
        public DateTime LessonDate { get; set; }
        
        [Display(Name ="Lesson Time")]
        [DataType(DataType.Time)]
        public DateTime LessonTime { get; set; }

        [Display(Name ="Duration & Cost")]
        [ForeignKey("DurationCost")]
        public int DurationCostId { get; set; }

        //Letter ID

        public Boolean Paid { get; set; }

        public virtual Student Student { get; set; }
        public virtual Instrument Instrument { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual DurationCost DurationCost { get; set; }
    }
}

Assignment1/Assignment1/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assignment1.Data;
using Assignment1.Models;

namespace Assignment1.Controllers
{
    public class LessonsController : Controller
    {
        private readonly Assignment1Context _context;

        public LessonsController(Assignment1Context context)
        {
            _context = context;
        }

        // GET: Lessons
        public async Task<IActionResult> Index(string searchString)
        {
            // var assignment1Context = _context.Lesson.Include(l => l.DurationCost).Include(l => l.Instrument).Include(l => l.Student).Include(l => l.Tutor);
            var lessons = from l in _context.Lesson
                          select l;

            if (!String.IsNullOrEmpty(searchString))
            {
                lessons = lessons.Where(l => l.Student.StudentFirstName.Contains(searchString));
            }

            lessons = lessons.Include(l => l.DurationCost).Include(l => l.Instrument).Include(l => l.Student).Include(l => l.Tutor);

            return View(await lessons.ToListAsync());
            
        }


        // GET: Lessons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lesson
                .Include(l => l.DurationCost)
                .Include(l => l.Instrument)
                .Include(l => l.Student)
                .Include(l => l.Tutor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }

        // GET: Lessons/Create
        public IActionResult Create()
        {
            ViewData["DurationCostId"] = new SelectList(_context.DurationCost, "Id", "LessonDurationCost");
            ViewData["InstrumentId"] = new SelectList(_context.Instrument, "Id", "StudentInstrument");
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "StudentFullName");
            ViewData["TutorId"] = new SelectList(_context.Tutor, "Id", "TutorFullName");
            return View();
        }

        // POST: Lessons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentId,InstrumentId,TutorId,LessonDate,LessonTime,DurationCostId,Checkbox")] Lesson lesson)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lesson);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DurationCostId"] = new SelectList(_context.DurationCost, "Id", "Id", lesson.DurationCostId);
            ViewData["InstrumentId"] = new SelectList(_context.Instrument, "Id", "Id", lesson.InstrumentId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", lesson.StudentId);
            ViewData["TutorId"] = new SelectList(_context.Tutor, "Id", "Id", lesson.TutorId);
            return View(lesson);
        }

        // GET: Lessons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lesson.FindAsync(id);
            if (lesson == null)
            {
                return NotFound();
            }
            ViewData["DurationCostId"] = new SelectList(_context.DurationCost, "Id", "LessonDurationCost", lesson.DurationCostId);
            ViewData["InstrumentId"] = new SelectList(_context.Instrument, "Id", "StudentInstrument", lesson.InstrumentId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "StudentFullName", lesson.StudentId);
            ViewData["TutorId"] = new SelectList(_context.Tutor, "Id", "TutorFullName", lesson.TutorId);
            return View(lesson);
        }

        // POST: Lessons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudentId,InstrumentId,TutorId,LessonDate,LessonTime,DurationCostId,Checkbox")] Lesson lesson)
        {
            if (id != lesson.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lesson);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LessonExists(lesson.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DurationCostId"] = new SelectList(_context.DurationCost, "Id", "Id", lesson.DurationCostId);
            ViewData["InstrumentId"] = new SelectList(_context.Instrument, "Id", "Id", lesson.InstrumentId);
            ViewData["StudentId"] = new SelectList(_context.Student, "Id", "Id", lesson.StudentId);
            ViewData["TutorId"] = new SelectList(_context.Tutor, "Id", "Id", lesson.TutorId);
            return View(lesson);
        }

        // GET: Lessons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lesson = await _context.Lesson
                .Include(l => l.DurationCost)
                .Include(l => l.Instrument)
                .Include(l => l.Student)
                .Include(l => l.Tutor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lesson == null)
            {
                return NotFound();
            }

            return View(lesson);
        }

        // POST: Lessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lesson = await _context.Lesson.FindAsync(id);
            _context.Lesson.Remove(lesson);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LessonExists(int id)
        {
            return _context.Lesson.Any(e => e.Id == id);
        }
    }
}

Assignment1/Assignment1/Views/Lessons/Create.cshtml
@model Assignment1.Models.Lesson

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Lesson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class ="form-control" asp-items="ViewBag.StudentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentId" class="control-label"></label>
                <select asp-for="InstrumentId" class ="form-control" asp-items="ViewBag.InstrumentId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TutorId" class="control-label"></label>
                <select asp-for="TutorId" class ="form-control" asp-items="ViewBag.TutorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LessonDate" class="control-label"></label>
                <input asp-for="LessonDate" class="form-control" />
                <span asp-validation-for="LessonDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LessonTime" class="control-label"></label>
                <input asp-for="LessonTime" class="form-control" />
                <span asp-validation-for="LessonTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DurationCostId" class="control-label"></label>
                <select asp-for="DurationCostId" class ="form-control" asp-items="ViewBag.DurationCostId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Paid" /> @Html.DisplayNameFor(model => model.Paid)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assignment1/Assignment1/Views/Lessons/Delete.cshtml
@model Assignment1.Models.Lesson

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lesson</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LessonDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LessonDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LessonTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LessonTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Paid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Paid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.StudentFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Instrument)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Instrument.StudentInstrument)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tutor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tutor.TutorFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DurationCost)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DurationCost.LessonDurationCost)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Assignment1/Assignment1/Views/Lessons/Details.cshtml
@model Assignment1.Models.Lesson

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Lesson</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LessonDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LessonDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LessonTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LessonTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Paid)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Paid)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Student)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Student.StudentFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Instrument)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Instrument.StudentInstrument)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tutor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tutor.TutorFullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DurationCost)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DurationCost.LessonDurationCost)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Assignment1/Assignment1/Views/Lessons/Edit.cshtml
@model Assignment1.Models.Lesson

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Lesson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <select asp-for="StudentId" class="form-control" asp-items="ViewBag.StudentId"></select>
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstrumentId" class="control-label"></label>
                <select asp-for="InstrumentId" class="form-control" asp-items="ViewBag.InstrumentId"></select>
                <span asp-validation-for="InstrumentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TutorId" class="control-label"></label>
                <select asp-for="TutorId" class="form-control" asp-items="ViewBag.TutorId"></select>
                <span asp-validation-for="TutorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LessonDate" class="control-label"></label>
                <input asp-for="LessonDate" class="form-control" />
                <span asp-validation-for="LessonDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LessonTime" class="control-label"></label>
                <input asp-for="LessonTime" class="form-control" />
                <span asp-validation-for="LessonTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DurationCostId" class="control-label"></label>
                <select asp-for="DurationCostId" class="form-control" asp-items="ViewBag.DurationCostId"></select>
                <span asp-validation-for="DurationCostId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Paid" /> @Html.DisplayNameFor(model => model.Paid)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assignment1/Assignment1/Views/Lessons/Index.cshtml
@model IEnumerable<Assignment1.Models.Lesson>

@{
    ViewData["Title"] = "Index";
}

<h1>Lessons Index</h1>

<p>
    <a asp-action="Create">Create New</a> |
    <a asp-action="placeholder">Calculate Letter</a>
</p>
<form asp-controller="Lessons" asp-action="Index" method="get">
    <p>
        Students First Name: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LessonDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LessonTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Student)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instrument)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tutor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DurationCost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {   
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LessonDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LessonTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Paid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.StudentFullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Instrument.StudentInstrument)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tutor.TutorFullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DurationCost.LessonDurationCost)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
            </td>
        </tr>
}
    </tbody>
</table>